"""config package — central settings loaded from environment / .env file."""
from config.settings import (
    OLLAMA_BASE_URL, LLM_MODEL, MOCK_LLM,
    DEDUP_SIMILARITY_THRESHOLD, HUMAN_REVIEW_THRESHOLD,
    REQUIRED_FIELDS, CATEGORY_TAXONOMY, COLOR_MAP, ATTRIBUTE_ALIASES,
    DATA_INPUT_DIR, DATA_OUTPUT_DIR, LOG_DIR,
)

__all__ = [
    "OLLAMA_BASE_URL", "LLM_MODEL", "MOCK_LLM",
    "DEDUP_SIMILARITY_THRESHOLD", "HUMAN_REVIEW_THRESHOLD",
    "REQUIRED_FIELDS", "CATEGORY_TAXONOMY", "COLOR_MAP", "ATTRIBUTE_ALIASES",
    "DATA_INPUT_DIR", "DATA_OUTPUT_DIR", "LOG_DIR",
]
